---
apiVersion: v2
name: edc-consumer-controlplane
description: EDC Control-Plane
home: https://github.com/catenax-ng/product-edc/deployment/helm/edc-controlplane
type: application
appVersion: "0.0.3"
version: 0.0.3
maintainers: []