version: '3.8'

services:
  irs:
    build:
      context: .
      target: irs-api
      args:
        BUILD_TARGET: irs-api
    profiles:
      - irs
    container_name: irs
    ports:
      - "8080:8080"
      - "4004:4004"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "${APPLICATIONINSIGHTS_CONNECTION_STRING}"
      APPLICATIONINSIGHTS_ROLE_NAME: IRS

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    volumes:
      - ./dev/prometheus/:/etc/prometheus/
    profiles:
      - debug
    ports:
      - "9091:9090"


  minio:
    image: quay.io/minio/minio:RELEASE.2022-04-01T03-41-39Z
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    ports:
      # Bind explicitly to 127.0.0.1
      - "127.0.0.1:9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - miniodata:/data

volumes:
  miniodata:
