# Copyright (c) 2021,2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0. *
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bdrs.fullname" . }}
  labels:
    {{- include "bdrs.labels" . | nindent 4 }}
data:
  bdrs_request.json: |-
    {
      "request": {
        "method": "GET",
        "urlPath": "/api/directory/bpn-directory"
      },
      "response": {
        "status": 200,
        "bodyFileName": "bdrs_response.json",
        "headers": {
          "Content-Type": "application/json"
        }
      }
    }

  bdrs_response.json: |-
    {
      "BPNL00000007QG00": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RI31": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003CSAP": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RNYV": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003CPIY": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL000000002YWC": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007R99A": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007ZS71": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003AZQP": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007QFU4": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000002HCQ9": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RF54": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000000BSNC": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003COJN": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL0000000711QM": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL0073928UJ879": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RWSM": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RTUP": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNLSIEMENSWE001": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RZQJ": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003BS6K": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RK1N": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007ZS7X": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00389SO09211": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007QNOK": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003CTG6": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003LLHB": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003CQI9": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RYR8": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003BR79": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003CRHK": "{{.Values.trustedIssuer}}",
      "BPNL00000007S7KZ": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RH3Q": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RVTB": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000001CRHK": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007QGTF": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003CML1": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007QJRC": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000007RXRX": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000000DFH0": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL001000TS0100": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL00000003CNKC": "{{ .Values.didPrefix }}:BPNL00000001CRHK",
      "BPNL0073928UJ000": "{{ .Values.didPrefix }}:BPNL00000001CRHK"
    }
