# INT values for aas wrapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/catenax-ng/catenax-at-home/consumer-api-wrapper
  tag: "0.0.4"

service:
  type: ClusterIP
  port: 9196

serviceCallback:
  type: ClusterIP
  port: 9197

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: "irs-aas-wrapper-pen.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: aaswrapper-pen
              port:
                number: 9196
  tls:
    - hosts:
        - "irs-aas-wrapper-pen.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

configuration:
  properties: |-
    web.http.port=9196
    web.http.path=/api
    web.http.callback.port=9197
    web.http.callback.path=/callback
    # wrapper.auth.basic.someuser=somepassword
    wrapper.consumer.edc.datamanagement.url=http://edc-consumer-controlplane:8181/data
    wrapper.consumer.edc.control.url=http://edc-consumer-controlplane:9999/api/controlplane/control
    wrapper.consumer.edc.apikey.name=X-Api-Key
    wrapper.consumer.edc.apikey.value=123456