---
replicaCount: 1

image:
  repository: ghcr.io/catenax-ng/registry@sha256
  pullPolicy: IfNotPresent
  tag: "d171ff49f5daa77631829915f3f02a6ffa2ce05995df1d604ea808d8f3ba55ed"

serviceAccount:
  create: true
  annotations: {}
  name: ""

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

containerPort: 4243
service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 750m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

authentication: false
enablePostgres: true
dataSource:
    driverClassName: org.postgresql.Driver
    sqlInitPlatform: pg

registry:
  containerPort: 4243
  service:
    port: 8080
    type: ClusterIP

  dockerSecret: ""
  imagePullSecrets:
    - name: dockerpullsecret
  ## If 'authentication' is set to false, no OAuth authentication is enforced

  ingress:
    enabled: false