---
apiVersion: v2
name: edc-dataplane-provider
description: >-
  EDC Data-Plane - The Eclipse DataSpaceConnector data layer with responsibility of transferring and receiving data streams
home: https://github.com/catenax-ng/product-edc/deployment/helm/edc-dataplane
type: application
appVersion: "0.2.0"
version: 0.2.0
maintainers: []