springprofile: dev

image:
  tag: $ARGOCD_APP_REVISION

nameOverride: "app-irs-dev"
fullnameOverride: "app-irs-dev"  

keycloak:
  oauth2:
    clientId: <path:traceability-irs/data/dev/keycloak/oauth2#clientId>
    clientSecret: <path:traceability-irs/data/dev/keycloak/oauth2#clientSecret>
    clientTokenUri: <path:traceability-irs/data/dev/keycloak/oauth2#tokenUri>
    jwkSetUri: <path:traceability-irs/data/dev/keycloak/oauth2#jwkSetUri>

aasProxy:
  submodel:
    username: <path:traceability-irs/data/dev/aasProxy/submodel#username>
    password: <path:traceability-irs/data/dev/aasProxy/submodel#password>

minio:
  url: http://app-minio-dev:9000

rootUser: <path:traceability-irs/data/dev/minio#minioUser>
rootPassword: <path:traceability-irs/data/dev/minio#minioPassword>

digitalTwinRegistry:
  url: https://irs-aas-registry.dev.demo.catena-x.net