springprofile: int

image:
  tag: $ARGOCD_APP_REVISION

ingress:
  hosts:
    - host: "irs.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "irs.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

keycloak:
  oauth2:
    clientId: <path:product-traceability-irs/data/int/keycloak/oauth2#clientId>
    clientSecret: <path:product-traceability-irs/data/int/keycloak/oauth2#clientSecret>
    clientTokenUri: <path:product-traceability-irs/data/int/keycloak/oauth2#tokenUri>
    jwkSetUri: <path:product-traceability-irs/data/int/keycloak/oauth2#jwkSetUri>

aasProxy:
  submodel:
    username: <path:product-traceability-irs/data/int/aasProxy/submodel#username>
    password: <path:product-traceability-irs/data/int/aasProxy/submodel#password>
