springprofile: esr

image:
  tag: main

ingress:
  hosts:
    - host: "irs-esr.dev.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "irs-esr.dev.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

keycloak:
  oauth2:
    clientId: <path:traceability-irs/data/dev/keycloak/oauth2#clientId>
    clientSecret: <path:traceability-irs/data/dev/keycloak/oauth2#clientSecret>
    clientTokenUri: <path:traceability-irs/data/dev/keycloak/oauth2#tokenUri>
    jwkSetUri: <path:traceability-irs/data/dev/keycloak/oauth2#jwkSetUri>

aasProxy:
  submodel:
    username: <path:traceability-irs/data/dev/aasProxy/submodel#username>
    password: <path:traceability-irs/data/dev/aasProxy/submodel#password>

minio:
  url: http://app-minio-esr:9000

aasWrapper:
  host: http://aaswrapper-esr:9191/api/service

digitalTwinRegistry:
  url: https://semantics.int.demo.catena-x.net/registry

rootUser: <path:traceability-irs/data/dev/minio#minioUser>
rootPassword: <path:traceability-irs/data/dev/minio#minioPassword>