springprofile: int

image:
  tag: $ARGOCD_APP_REVISION

nameOverride: "app-irs-int"
fullnameOverride: "app-irs-int"  


ingress:
  hosts:
    - host: "irs.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "irs.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

keycloak:
  oauth2:
    clientId: <path:traceability-irs/data/int/keycloak/oauth2#clientId>
    clientSecret: <path:traceability-irs/data/int/keycloak/oauth2#clientSecret>
    clientTokenUri: <path:traceability-irs/data/int/keycloak/oauth2#tokenUri>
    jwkSetUri: <path:traceability-irs/data/int/keycloak/oauth2#jwkSetUri>

aasProxy:
  submodel:
    username: <path:traceability-irs/data/int/aasProxy/submodel#username>
    password: <path:traceability-irs/data/int/aasProxy/submodel#password>

minio:
  url: http://app-irs-int-minio:9000

rootUser: <path:traceability-irs/data/int/minio#minioUser>
rootPassword: <path:traceability-irs/data/int/minio#minioPassword>    
