---
{{ if .Values.install.edc.consumer }}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: edc-consumer-database-pv-claim
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    app: postgres
    db: edc-consumer
  annotations:
    "helm.sh/resource-policy": keep    
spec:
  storageClassName: standard
  volumeName: edc-consumer-database-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

{{ end }}