---
replicaCount: 1

# Which image should be used here?
image:
  repository: ghcr.io/catenax-ng/product-edc/edc-dataplane-hashicorp-vault
  pullPolicy: IfNotPresent
  tag: "0.3.0"

serviceAccount:
  create: true
  annotations: {}
  name: ""

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true
  failureThreshold: 12
  initialDelaySeconds: 10

service:
  type: ClusterIP

resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 0.25Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

logging:
  properties: |-
    .level=DEBUG
    org.eclipse.dataspaceconnector.level=ALL
    handlers=java.util.logging.ConsoleHandler
    java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
    java.util.logging.ConsoleHandler.level=ALL
    java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

opentelemetry:
  properties: |-
    otel.javaagent.enabled=false
    otel.javaagent.debug=false

edc:
  endpoints:
    default:
      port: "8080"
      path: /api
    public:
      port: "8185"
      path: /api/public
    control:
      port: "9999"
      path: /api/dataplane/control
    metrics:
      port: "9090"
      path: /metrics

ingresses:
  - enabled: false
