bdrs-server-memory:
   server:
     env:
       EDC_IAM_TRUSTED-ISSUER_ISSUER_ID: "did:web:irs-bdrs.dev.demo.catena-x.net:BPNTEST"
       EDC_IAM_DID_WEB_USE_HTTPS: "false"
     endpoints:
       # -- default api for health checks, should not be added to any ingress
       default:
         # -- port for incoming api calls
         port: 8080
         # -- path for incoming api calls
         path: /api
       # -- management api, used by internal users, can be added to an ingress and must not be internet facing
       management:
         # -- port for incoming api calls
         port: 8081
         # -- path for incoming api calls
         path: /api/management
         # -- authentication key, must be attached to each 'X-Api-Key' request header
         authKey: <path:traceability-irs/data/dev/controlplane#apiKey>
       # -- directory API
       directory:
         # -- port for incoming api calls
         port: 8082
         # -- path for incoming api calls
         path: /api/directory

     ingresses:
       - enabled: true
         hostname: "irs-bdrs.dev.demo.catena-x.net"
         annotations:
           nginx.ingress.kubernetes.io/ssl-passthrough: "false"
           nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
           nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
         endpoints:
           - management
           - directory
         tls:
           enabled: true
           secretName: tls-secret
         className: "nginx"
