fullnameOverride: "spike"

auth:
  postgresPassword: postgrespassword
  username: "edc"
  password: databasepassword
  database: "edc"
#primary:
#  initdb:
#    scripts:
#      init.sql: |
#        CREATE USER irs WITH PASSWORD 'irspass';
#        CREATE DATABASE edc;
#        GRANT ALL PRIVILEGES ON DATABASE edc TO irs;
#        CREATE DATABASE edc-consumer;
#        GRANT ALL PRIVILEGES ON DATABASE edc-consumer TO irs;