---
apiVersion: v2
name: edc-controlplane-provider
description: EDC Control-Plane
home: https://github.com/catenax-ng/product-edc/deployment/helm/edc-controlplane
type: application
appVersion: "0.2.0"
version: 0.2.0
maintainers: []