irs-helm:
  #####################
  # IRS Configuration #
  #####################
  irsUrl: "https://irs.int.demo.catena-x.net"
  bpn: BPNL00000001CRHK
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: "irs.int.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "irs.int.demo.catena-x.net"
        secretName: tls-secret
  digitalTwinRegistry:
    url: https://semantics.int.demo.catena-x.net/registry
    discoveryFinderUrl: https://semantics.int.demo.catena-x.net/discoveryfinder/api/administration/connectors/discovery/search
  semanticshub:
    url: https://semantics.int.demo.catena-x.net/hub/api/v1/models
    pageSize: "200"
  bpdm:
    url: https://partners-pool.int.demo.catena-x.net
  minioUser: <path:traceability-irs/data/int/minio#minioUser>
  minioPassword: <path:traceability-irs/data/int/minio#minioPassword>
  keycloak:
    oauth2:
      clientId: <path:traceability-irs/data/int/keycloak/oauth2#clientId>
      clientSecret: <path:traceability-irs/data/int/keycloak/oauth2#clientSecret>
      clientTokenUri: <path:traceability-irs/data/int/keycloak/oauth2#tokenUri>
      jwkSetUri: <path:traceability-irs/data/int/keycloak/oauth2#jwkSetUri>
  portal:
    oauth2:
      clientId: <path:traceability-irs/data/int/keycloak/dataspacediscovery#clientId>
      clientSecret: <path:traceability-irs/data/int/keycloak/dataspacediscovery#clientSecret>
  edc:
    provider:
      host:
    controlplane:
      apikey:
        secret: <path:traceability-irs/data/int/controlplane#apiKey>
    catalog:
      cache:
        enabled: false


  #######################
  # Minio Configuration #
  #######################
  minio:
    rootUser: <path:traceability-irs/data/int/minio#minioUser>
    rootPassword: <path:traceability-irs/data/int/minio#minioPassword>
    serviceAccount:
      name: "irs-int-minio-sa"

  #########################
  # Grafana Configuration #
  #########################
  grafana:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - "irs-grafana.int.demo.catena-x.net"
      tls:
        - hosts:
            - "irs-grafana.int.demo.catena-x.net"
          secretName: tls-secret

    user: <path:traceability-irs/data/int/grafana#username>
    password: <path:traceability-irs/data/int/grafana#password>

  ############################
  # Prometheus Configuration #
  ############################
  prometheus:
    enabled: true



tractusx-connector:
  install:
    postgresql: false
    daps: false
    vault: false
  participant:
    id: BPNL00000003CRHK

  controlplane:
    ingresses:
      - enabled: true
        hostname: "irs-consumer-controlplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

    endpoints:
      # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
      management:
        port: 8081
        path: /management
        authKey: <path:traceability-irs/data/int/controlplane#apiKey>  # -- authentication key, must be attached to each 'X-Api-Key' request header
      # -- protocol api, used for inter connector communication and must be internet facing
      protocol:
        port: 8084
        path: /api/v1/dsp
      # -- observability api with unsecured access, must not be internet facing
      observability:
        port: 8085
        path: /observability  # -- observability api, provides /health /readiness and /liveness endpoints
        insecure: true  # -- allow or disallow insecure access, i.e. access without authentication

    internationalDataSpaces:
      id: TXDC
      description: Tractus-X Eclipse IDS Data Space Connector
      title: "IRS INT Consumer EDC"
      maintainer: ""
      curator: ""
      catalogId: TXDC-Catalog

    # Explicitly declared url for reaching the ids api (e.g. if ingresses not used)
    url:
      ids: ""

    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi

  dataplane:
    ## Ingress declaration to expose the network service.
    ingresses:
      ## Public / Internet facing Ingress
      - enabled: true
        # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
        hostname: "irs-consumer-dataplane.int.demo.catena-x.net"
        # -- Additional ingress annotations to add
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        # -- EDC endpoints exposed by this ingress resource
        endpoints:
          - public
        # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
        className: "nginx"
        # -- Enables TLS on the ingress resource
        tls:
          enabled: true
          secretName: tls-secret

    endpoints:
      public:
        port: 8081
        path: /api/public
      observability:
        port: 8085
        path: /observability
        insecure: true

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi

  # URL where the EndpointDataReference callback will be sent to
  backendService:
    httpProxyTokenReceiverUrl: "http://app-irs-int-irs-helm:8181/internal/endpoint-data-reference"

  ################################
  # EDC Vault/DAPS Configuration #
  ################################
  vault:
    hashicorp:
      url: "https://vault.demo.catena-x.net"
      token: "<path:traceability-irs/data/int/controlplane#vaultToken>"
      timeout: 30
      healthCheck:
        enabled: true
        standbyOk: true
      paths:
        secret: /v1/traceability-irs
        health: /v1/sys/health
    secretNames:
      transferProxyTokenSignerPrivateKey: irs-int-daps-key
      transferProxyTokenSignerPublicKey: irs-int-daps-cert
      transferProxyTokenEncryptionAesKey: test-edc-encryption-key
      dapsPrivateKey: irs-int-daps-key
      dapsPublicKey: irs-int-daps-cert

  daps:
    url: "https://daps1.int.demo.catena-x.net"
    clientId: <path:traceability-irs/data/int/controlplane#edc.oauth.client.id>
    paths:
      jwks: /.well-known/jwks.json
      token: /token

  ##################################
  # EDC Postgres Configuration #
  ##################################
  postgresql:
    enabled: true
    auth:
      username: <path:traceability-irs/data/int/controlplane#databaseuser>
      password: <path:traceability-irs/data/int/controlplane#databasepassword>
    username: <path:traceability-irs/data/int/controlplane#databaseuser>
    password: <path:traceability-irs/data/int/controlplane#databasepassword>
    jdbcUrl: "jdbc:postgresql://app-irs-int-edc-postgresql-hl:5432/edc"

##############################
# EDC Postgres Configuration #
##############################
# EDC chart do not support multiple postgres instances in the same namespace at the moment.
# Enable this to use the postgres dependency for when you want to deploy multiple EDC instances in one namespace
postgresql:
  enabled: true
edc-postgresql:
  auth:
    database: edc
    username: <path:traceability-irs/data/int/controlplane#databaseuser>
    postgresPassword: <path:traceability-irs/data/int/controlplane#databasepassword>
    password: <path:traceability-irs/data/int/controlplane#databasepassword>
