---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-configmap
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    {{- .Values.config | nindent 4 }}
