---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-configmap
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  prometheus.yml:
    {{- toYaml . | nindent 4 }}
  {{- end }}
