tractusx-connector:
  participant:
    id: <path:traceability-irs/data/dev/controlplane#participantId>

  controlplane:
    ingresses:
      - enabled: true
        hostname: "irs-provider-controlplane-test.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

  dataplane:
    ingresses:
      - enabled: true
        hostname: "irs-provider-dataplane-test.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

  backendService:
    httpProxyTokenReceiverUrl: "https://irs-submodel-server.dev.demo.catena-x.net/data/endpoint-data-reference-provider-test"

  vault:
    hashicorp:
      healthCheck:
        enabled: false
        standbyOk: false
    secretNames:
      transferProxyTokenSignerPrivateKey: dev-provider3-key
      transferProxyTokenSignerPublicKey: dev-provider3-cert
      transferProxyTokenEncryptionAesKey: test-edc-encryption-key

  postgresql:
    jdbcUrl: "jdbc:postgresql://irs-provider-test-edc-postgresql-hl:5432/edc"
