---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "digital-twin-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "digital-twin-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "digital-twin-registry.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "digital-twin-registry.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if not .Values.authentication }}
          args: ["--spring.profiles.active=local"]
          {{- end }}
          ports:
            - name: default
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: default
            initialDelaySeconds: 100
            periodSeconds: 3
            failureThreshold: 3
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: default
            initialDelaySeconds: 60
            periodSeconds: 3
            failureThreshold: 3
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
            - secretRef:
                name: {{ .Values.registry.secret.name }}
          resources:
          {{ .Values.resources | toYaml | indent 12 }}
      imagePullSecrets:
      {{ .Values.registry.imagePullSecrets | toYaml | indent 8 }}
