name: IRS BETA Cucumber Integration test Xray execution

on:
  workflow_dispatch: # Trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Download Feature Files
        id: download
        env:
          JIRA_USERNAME: ${{ secrets.ORG_IRS_JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.ORG_IRS_JIRA_PASSWORD }}
          # JIRA filter 11590: project = "TRI" AND type = Test AND "Test Type" = Cucumber AND environment ~ Beta
          # Downloads all feature files of cucumber tests inside TRI project
        run: |
          export HTTP_RESULT=$(curl -s --show-error -w "%{http_code}" -u $JIRA_USERNAME:$JIRA_PASSWORD "https://jira.catena-x.net/rest/raven/1.0/export/test?filter=11590&fz=true" -o features.zip)
          [[ $HTTP_RESULT == 200 || $HTTP_RESULT == 400 ]]
          echo "::set-output name=http_response::$HTTP_RESULT"

      - name: Build with Maven
        if: ${{ steps.download.outputs.http_response == '200' }}
        env:
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_SECRET_BETA }}
        run: |
          unzip -o features.zip -d irs-cucumber-tests/src/test/resources/features
          mvn --batch-mode clean install -pl irs-cucumber-tests,irs-models -D"cucumber.filter.tags"="not @Ignore and @INTEGRATION_TEST"

      - name: Submit results to Xray
        if: ${{ always() && steps.download.outputs.http_response == '200' }}
        env:
          JIRA_USERNAME: ${{ secrets.ORG_IRS_JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.ORG_IRS_JIRA_PASSWORD }}
        run: |
          curl --request POST -u $JIRA_USERNAME:$JIRA_PASSWORD --header 'Content-Type: application/json' --data-binary '@irs-cucumber-tests/report.json' "https://jira.catena-x.net/rest/raven/1.0/import/execution/cucumber"
