name: IRS Cucumber Integration Test execution

on:
  workflow_call: # Trigger by another workflow
    secrets:
      regularUserApiKey:
        required: true
      adminUserApiKey:
        required: true
      cucumberPublishToken:
        required: true
    inputs:
      executionFilter:
        required: true
        type: string

jobs:

  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required secrets
        run: |
          CONFIG_OK=false
          
          if [[ -z "${{ secrets.regularUserApiKey }}" ]]; then
            echo "Missing secret: Please configure the regular user API key."
            CONFIG_OK=true
          fi
          
          if [[ -z "${{ secrets.adminUserApiKey }}" ]]; then
            echo "Missing secret: Please configure the admin user API key."
            CONFIG_OK=true
          fi
          
          if [[ -z "${{ secrets.cucumberPublishToken }}" ]]; then
            echo "Missing secret: Please confifure the cucumber publish token."
            CONFIG_OK=true
          fi
          
          if [ "$CONFIG_OK" = true ]; then
            exit 1
          fi
        shell: bash

  build:
    needs: check-config
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests with Maven
        env:
          REGULAR_USER_API_KEY: ${{ secrets.regularUserApiKey }}
          ADMIN_USER_API_KEY: ${{ secrets.adminUserApiKey }}
          ISSUE_FILTER: ${{ inputs.executionFilter }}
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.cucumberPublishToken }}
        # workaround replacement since injecting the token via environment variable does not work
        run: |
          sed -i "s/CUCUMBER_TOKEN_IRS_PLACEHOLDER/${CUCUMBER_PUBLISH_TOKEN}/g" irs-cucumber-tests/src/test/java/org/eclipse/tractusx/irs/cucumber/RunCucumberTest.java

          mvn clean verify -P cucumber -Dgroups="$ISSUE_FILTER" -pl irs-cucumber-tests -am --batch-mode 2> irs-cucumber-tests/report-banner.txt

      - name: Publish Cucumber Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          files: |
            irs-cucumber-tests/target/cucumber-junit-report.xml

      - name: Get Cucumber Report
        if: always()
        id: get-cucumber-report
        run: |
          grep -E "^│.*│$" irs-cucumber-tests/report-banner.txt > irs-cucumber-tests/cucumber-report.txt
          sed -i 's/│//g' irs-cucumber-tests/cucumber-report.txt
          cat irs-cucumber-tests/cucumber-report.txt
          cat irs-cucumber-tests/cucumber-report.txt >> $GITHUB_STEP_SUMMARY

      - name: Find previous comment in PR
        if: always() && github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'View your Cucumber Report at'

      - name: Create or update comment in PR
        if: always() && github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'irs-cucumber-tests/cucumber-report.txt'
          edit-mode: replace

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: 'irs-cucumber-tests/target/report.html'
