name: IRS DEV Cucumber Integration test execution

on:
  workflow_dispatch: # Trigger manually
    inputs:
      additionalFilter:
        description: 'Additional execution filter'
        required: false
        default: ''
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'charts/**'
      - '.config/**'
      - 'docs/**'
      - 'local/**'
      - 'irs-load-tests/**'

# Cancel previous Test executions if a new one is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true




jobs:

  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check if DEV_REGULAR_USER_API_KEY is defined
        run: |
          if [[ -z "${{ secrets.DEV_REGULAR_USER_API_KEY }}" ]]; then
            echo "Error: Missing secret: Please configure DEV_REGULAR_USER_API_KEY."
            exit 1
          fi
      - name: Check if DEV_ADMIN_USER_API_KEY is defined
        run: |
          if [[ -z "${{ secrets.DEV_ADMIN_USER_API_KEY }}" ]]; then
            echo "Error: Missing secret: Please configure DEV_ADMIN_USER_API_KEY."
            exit 1
          fi
  # TODO it this really required?
  #      - name: Check if IRS_CUCUMBER_PUBLISH_TOKEN is defined
  #        run: |
  #          if [[ -z "${{ secrets.IRS_CUCUMBER_PUBLISH_TOKEN }}" ]]; then
  #            echo "Error: Missing secret: Please configure IRS_CUCUMBER_PUBLISH_TOKEN."
  #            exit 1
  #          fi
  #        shell: bash


  prepare-execution-filter:
    runs-on: ubuntu-latest
    needs: check-config
    outputs:
      executionFilter: ${{ steps.set-filter.outputs.executionFilter }}
    steps:
      - name: Set execution filter
        id: set-filter
        run: |
          base_filter="!Ignore & !INACTIVE & INTEGRATION_TEST & DEV"
          if [ -n "${{ github.event.inputs.additionalFilter }}" ]; then
            execution_filter="${base_filter} & ${{ github.event.inputs.additionalFilter }}"
          else
            execution_filter="${base_filter}"
          fi
          echo "::set-output name=executionFilter::${execution_filter}"
          

  trigger-integration-test:
    needs: prepare-execution-filter
    uses: ./.github/workflows/cucumber-integration-test.yaml
    secrets:
      regularUserApiKey: ${{ secrets.DEV_REGULAR_USER_API_KEY }}
      adminUserApiKey: ${{ secrets.DEV_ADMIN_USER_API_KEY }}
      cucumberPublishToken: ${{ secrets.IRS_CUCUMBER_PUBLISH_TOKEN }}
    with:
      executionFilter: ${{ needs.prepare-execution-filter.outputs.executionFilter }}
