name: IRS Load Test

on:
  workflow_dispatch: # Trigger manually
    inputs:
      irs-host:
        type: choice
        description: IRS environment to test
        default: 'https://irs-full.dev.demo.catena-x.net'
        required: true
        options:
          - 'https://irs-full.dev.demo.catena-x.net'
          - 'https://irs.dev.demo.catena-x.net'
          - 'https://irs.int.demo.catena-x.net'
      test-cycles:
        type: string
        description: Number of Test Cycles
        default: '20'
        required: false

jobs:
  gatling-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Gatling tests
        env:
          OAUTH2_HOST: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI }}
          OAUTH2_CLIENT_SECRET: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_SECRET }}
          OAUTH2_CLIENT_ID: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_ID }}
          IRS_HOST: ${{ github.event.inputs.irs-host || 'https://irs-full.dev.demo.catena-x.net' }}
          TEST_CYCLES: ${{ github.event.inputs.test-cycles || '20' }}
        run: |
          mvn gatling:test -pl irs-load-tests

      - name: Archive Report
        uses: actions/upload-artifact@v3
        with:
          name: gatling-report
          path: irs-load-tests/target/gatling/
