name: IRS TEST Setup Test Data

on:
  workflow_dispatch:
    inputs:
      testfilePath:
        description: 'Path to Testdata file on GitHub'
        required: true
        type: string
      submodelUrl1:
        description: 'URL for Submodel server 1'
        required: true
        type: string
      submodelUrl2:
        description: 'URL for Submodel server 2'
        required: true
        type: string
      submodelUrl3:
        description: 'URL for Submodel server 3'
        required: true
        type: string
      aasUrl:
        description: 'Digital twin registry URL'
        required: true
        type: string
      edcUrl1:
        description: 'Provider 1 control plane URL'
        required: true
        type: string
      edcUrl2:
        description: 'Provider 2 control plane URL'
        required: true
        type: string
      edcUrl3:
        description: 'Provider 3 control plane URL'
        required: true
        type: string
      edcApiKey:
        description: 'API-Key for the provider control plane'
        required: true
        type: string
      esrUrl:
        description: 'ESR endpoint Url'
        required: false
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
          cache: 'pip'
      - run: pip install -r testdata-transform/requirements.txt

      - name: Delete existing and setup new test data on provider EDC and Registry
        env:
          TESTFILE_PATH: ${{ github.event.inputs.testfilePath }}
          SUBMODEL_URL_1: ${{ github.event.inputs.submodelUrl1 }}
          SUBMODEL_URL_2: ${{ github.event.inputs.submodelUrl2 }}
          SUBMODEL_URL_3: ${{ github.event.inputs.submodelUrl3 }}
          AAS_URL: ${{ github.event.inputs.aasUrl }}
          EDC_URL_1: ${{ github.event.inputs.edcUrl1 }}
          EDC_URL_2: ${{ github.event.inputs.edcUrl2 }}
          EDC_URL_3: ${{ github.event.inputs.edcUrl3 }}
          EDC_API_KEY: ${{ github.event.inputs.edcApiKey }}
          ESR_URL: ${{ github.event.inputs.esrUrl }}
        run: |
          python testdata-transform/reset-env.py \
          -a $AAS_URL \
          -e1 EDC_URL_1 \
          -e2 EDC_URL_2 \
          -e3 EDC_URL_3 \
          -k $EDC_API_KEY
          python testdata-transform/transform-and-upload.py \
          -f $TESTFILE_PATH \
          -s1 $SUBMODEL_URL_1 \
          -s2 $SUBMODEL_URL_2 \
          -s3 $SUBMODEL_URL_3 \
          -a $AAS_URL \
          -e1 EDC_URL_1 \
          -e2 EDC_URL_2 \
          -e3 EDC_URL_3 \
          -k $EDC_API_KEY \
          -e $ESR_URL
