name: IRS TEST Setup Test Data

on:
  workflow_dispatch:
    inputs:
      testfilePath:
        description: 'Path to Testdata file on GitHub'
        required: true
        type: string
      submodelUrl1:
        description: 'URL for Submodel server 1'
        required: true
        type: string
      submodelUrl2:
        description: 'URL for Submodel server 2'
        required: true
        type: string
      submodelUrl3:
        description: 'URL for Submodel server 3'
        required: true
        type: string
      internalProviderControlPlane:
        description: 'Internal provider control plane URL of ids port'
        required: true
        type: string
      aasUrl:
        description: 'Digital twin registry URL'
        required: true
        type: string
      edcUrl:
        description: 'Provider control plane URL'
        required: true
        type: string
      edcApiKey:
        description: 'API-Key for the provider control plane'
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Setup Test Data on INT
        env:
          TESTFILE_PATH: ${{ github.event.inputs.testfilePath }}
          SUBMODEL_URL_1: ${{ github.event.inputs.submodelUrl1 }}
          SUBMODEL_URL_2: ${{ github.event.inputs.submodelUrl2 }}
          SUBMODEL_URL_3: ${{ github.event.inputs.submodelUrl3 }}
          INTERNAL_PROVIDER_CONTROL_PLANE: ${{ github.event.inputs.internalProviderControlPlane }}
          AAS_URL: ${{ github.event.inputs.aasUrl }}
          EDC_URL: ${{ github.event.inputs.edcUrl }}
          EDC_API_KEY: ${{ github.event.inputs.edcApiKey }}
        run: |
          python testdata-transform/transform-and-upload.py \
          -f $TESTFILE_PATH \
          -s1 $SUBMODEL_URL_1 \
          -s2 $SUBMODEL_URL_2 \
          -s3 $SUBMODEL_URL_3 \
          -i $INTERNAL_PROVIDER_CONTROL_PLANE \
          -a $AAS_URL \
          -e $EDC_URL \
          -k $EDC_API_KEY




  
  
  
  
  
  
  
  



