name: Update docs for IRS release

env:
  IRS_APPLICATION_PATH: 'irs-api/src/main/java/org/eclipse/tractusx/irs/IrsApplication.java'
  TOP_LEVEL_CHANGELOG_PATH: 'CHANGELOG.md'
  IRS_OPENAPI_SPEC_PATH: 'docs/src/api/irs-api.yaml'
  IRS_HELM_CHANGELOG_PATH: 'charts/item-relationship-service/CHANGELOG.md'
  SEMVER_PATTERN: '[0-9]+\.[0-9]+\.[0-9]+'

on:
  workflow_dispatch:
    inputs:
      irs-version:
        description: 'New IRS version'
        required: true
        type: string
      helm-chart-version:
        description: 'New Helm Chart version'
        required: true
        type: string
      helm-changelog-irs-added:
        description: '"Update IRS version to ..." change already present in charts/irs-helm/CHANGELOG.md for this release?'
        required: true
        type: choice
        options:
          - 'Yes'
          - 'No'
        default: 'No'
jobs:
  update-docs-for-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate that workflow inputs are SemVer strings
        run: |
          matched_irs_semver_string=$(echo "${{ inputs.irs-version }}" | grep -Ex "${{ env.SEMVER_PATTERN }}")
          matched_helm_chart_semver_string=$(echo "${{ inputs.helm-chart-version }}" | grep -Ex "${{ env.SEMVER_PATTERN }}")
          if [[ -z "$matched_irs_semver_string" || -z "$matched_helm_chart_semver_string" ]]; then
              exit 1
          fi
        continue-on-error: false

      - name: Validate that IRS and Helm Chart versions don't exist yet
        run: |
          # IRS version can be checked via git tag since every release has a tag
          matched_irs_version=$(git tag | grep -Eo "${{ inputs.irs-version }}" || echo "")
          # extract from Helm Chart changelog
          matched_helm_chart_version=$(grep -Eo "## \[${{ inputs.helm-chart-version }}\]" ${{ env.IRS_HELM_CHANGELOG_PATH }} || echo "")
          
          if [ -n "$matched_irs_version" ] || [ -n "$matched_helm_chart_version" ]; then
              echo "IRS or Helm Chart release version already exists, aborting..."
              exit 1
          fi
        continue-on-error: false

      - name: Update top level changelog, IRS Helm changelog, Helm repository's yaml file and IrsApplication.java
        run: |
          new_irs_version="${{ inputs.irs-version }}"
          new_helm_chart_version="${{ inputs.helm-chart-version }}"
          irs_change_present_in_helm_changelog="${{ inputs.helm-changelog-irs-added }}"
          date=$(date +"%Y-%m-%d")
          
          semver_pattern="${{ env.SEMVER_PATTERN }}"
          semver_pattern_sed="[0-9]\+\.[0-9]\+\.[0-9]\+"

          # get line numbers of "Unreleased" or "UNRELEASED" placeholders in changelogs to use them with sed
          top_lvl_changelog_placeholder_line_number=$(cat -n ${{ env.TOP_LEVEL_CHANGELOG_PATH }} | grep -Eoi "[0-9]+.## \[Unreleased\]" | grep -Eo "[0-9]+")
          irs_helm_changelog_placeholder_line_number=$(cat -n ${{ env.IRS_HELM_CHANGELOG_PATH }} | grep -Eoi "[0-9]+.## \[Unreleased\]" | grep -Eo "[0-9]+")
          
          ### update CHANGELOG.md ###
          # get line number of uppermost comparison url ("[Unreleased]: https://github.com/.../version...HEAD")
          latest_comparison_url_line_number=$(cat -n ${{ env.TOP_LEVEL_CHANGELOG_PATH }} | grep -Eoi "[0-9]+.\[Unreleased\]" | grep -Eo "[0-9]+")
          
          # previous version can be extracted from line below uppermost comparison
          previous_irs_version=$(awk "NR==$((latest_comparison_url_line_number+1))" ${{ env.TOP_LEVEL_CHANGELOG_PATH }} | grep -Eo "\[$semver_pattern\]" | tr -d "[]")
          
          # correct uppermost comparison
          sed -i "$latest_comparison_url_line_number s|$semver_pattern_sed\.\.\.HEAD|$new_irs_version...HEAD|" ${{ env.TOP_LEVEL_CHANGELOG_PATH }}         
          
          # insert new comparison below uppermost one
          sed -i "$((latest_comparison_url_line_number+1)) s|^|[$new_irs_version]: https://github.com/eclipse-tractusx/item-relationship-service/compare/$previous_irs_version...$new_irs_version\n|" ${{ env.TOP_LEVEL_CHANGELOG_PATH }}        
          
          # replace placeholder
          # get line numbers of "Unreleased" placeholder in changelogs to use them with sed
          top_lvl_changelog_placeholder_line_number=$(cat -n ${{ env.TOP_LEVEL_CHANGELOG_PATH }} | grep -Eoi "[0-9]+.## \[Unreleased\]" | grep -Eo "[0-9]+")
          sed -i "$((top_lvl_changelog_placeholder_line_number+1)) s|^|\n## [$new_irs_version] - $date\n|" ${{ env.TOP_LEVEL_CHANGELOG_PATH }}
          
          ### update irs-helm directory's CHANGELOG.md ###
          if [ "$irs_change_present_in_helm_changelog" = "No" ]; then
            # get line number of first header which is not placeholder
            next_header_line_number=$(cat -n ${{ env.IRS_HELM_CHANGELOG_PATH }} | grep -Eo -m 1 "[0-9]+.## \[$semver_pattern\]" | grep -Eo "^[0-9]+")
            # get line number of first  "### Changed" section
            first_changed_section_line_number=$(cat -n ${{ env.IRS_HELM_CHANGELOG_PATH }} | grep -Eo -m 1 "[0-9]+.### Changed" | grep -Eo "[0-9]+")
          
            # "### Changed" is already present for current changelog if it comes before next header -> just insert line below
            if [ $first_changed_section_line_number -lt $next_header_line_number ]; then
              sed -i "$((first_changed_section_line_number+1)) s|^|- Update IRS version to $new_irs_version\n|" ${{ env.IRS_HELM_CHANGELOG_PATH }}
            # not present, insert before beginning of next header
            else
              sed -i "$(($next_header_line_number-1)) s|^|\n### Changed\n- Update IRS version to $new_irs_version\n|" ${{ env.IRS_HELM_CHANGELOG_PATH }}
            fi
          fi
          
          # replace placeholder
          irs_helm_changelog_placeholder_line_number=$(cat -n ${{ env.IRS_HELM_CHANGELOG_PATH }} | grep -Eoi "[0-9]+.## \[Unreleased\]" | grep -Eo "[0-9]+")
          sed -i "$((irs_helm_changelog_placeholder_line_number+1)) s|^|\n## [$new_helm_chart_version] - $date\n|" ${{ env.IRS_HELM_CHANGELOG_PATH }}
          
          ### update irs-api.yaml ###
          irs_openapi_spec_irs_version_line_number=$(cat -n ${{ env.IRS_OPENAPI_SPEC_PATH }} | grep -Eo -m 1 "[0-9]+.+version: $semver_pattern" | grep -Eo "^[0-9]+")
          sed -i "$irs_openapi_spec_irs_version_line_number s|$semver_pattern_sed|$new_irs_version|" ${{ env.IRS_OPENAPI_SPEC_PATH }}  
          
          ### update IrsApplication.java ###
          sed -i "s|API_VERSION = \"$semver_pattern_sed\"|API_VERSION = \"$new_irs_version\"|" ${{ env.IRS_APPLICATION_PATH }}

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore(docs): Update docs for release ${{ inputs.irs-version }}'
          branch: chore/update-docs-for-irs-release-${{ inputs.irs-version }}
          base: main
          delete-branch: true
          title: Updated docs for next release
          body: This PR prepares the docs for IRS release version ${{ inputs.irs-version }}.
            Please check whether the docs were updated correctly.

      - name: Confirm that the pull request has been merged, then push git tag
        run: |
          pull_request_number=${{ steps.cpr.outputs.pull-request-number }}
          pull_request_merged="False"
          minutes_waited_for_merge=0
          # set duration between api requests
          sleep_interval_length=2
          
          while [ "$pull_request_merged" = "False" ]
          do
            # give some time to merge pull request
            sleep "$sleep_interval_length"m
          
            # retrieve the status of the pull request
            res=$(curl -L \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$pull_request_number)
          
            # response body contains field "merged_at" -> extract
            # "merged_at" will contain date time string when pr merged, otherwise it will be null
            date_time_pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z"
            merged_at=$(echo $res | grep -Eo "\"merged_at\": (null|\"$date_time_pattern\")" | grep -Eo "null|$date_time_pattern")            
          
          
            if [ "$merged_at" != "null" ]; then
              pull_request_merged="True"
            else
              minutes_waited_for_merge=$((minutes_waited_for_merge+sleep_interval_length))
          
              # abort workflow when having waited for 20 minutes
              if [ $minutes_waited_for_merge -gt 20 ]; then
                exit 1
              fi
            fi
          done
          
          git tag ${{ inputs.irs-version }} && git push origin ${{ inputs.irs-version }}
        continue-on-error: false

  call-release-workflow:
    needs:
      - update-docs-for-release
    uses: ./.github/workflows/release.yaml
    with:
      irs-version: ${{ inputs.irs-version }}